### PR TITLE
fix polylines ( update to 2.0.6 ) 

### PR DESCRIPTION
**Pull request by TetrixGauss**
Polylines version updated to latest with latest http package version to overcome security issue https://github.com/advisories/GHSA-4rgh-jx4f-qfcq

### CODE REVIEW

**Comment by TetrixGauss** [comment]
@abinvs-2019 can you merge please ( and i dont know, but can you put me to contributors may i ask? :D )

**Comment by TetrixGauss** [comment]
@abinvs-2019 can you please update the package regarding that PR?

**Review by abinvs-2019 — APPROVED** [review]
yeah LGTM

**Comment by abinvs-2019** [comment]
Hey @TetrixGauss i can make you contributor. i think We could make more updations on the package.

**Pull request merged**
